apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    uid: "b91f0c17-49e5-4d7a-8276-155583a40e37"
    url: coinfarm-vast-panel-db:3306
    user: grafana
    jsonData:
      database: vast
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: grafana