FROM grafana/grafana:latest

COPY ./default.yaml /etc/ffff
COPY default.yaml /etc/grafana/provisioning/datasources/default.yaml
# VOLUME "./dashboard.yml" "/etc/grafana/provisioning/dashboards/dashboard.yaml"
# VOLUME "/grafana/provisioning/dashboards/"
