{
 "title": "Farm overview",
 "description": "v0.1.0",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Machine reliability score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT Time as timestamp, Hostname, Reliability\r\nFROM machines"
    }
   ]
  },
  {
   "title": "Machine demand occupancy rate",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "vast",
     "rawSql": "SELECT Time as timestamp, Hostname, (NumGpusDemandOcc / NumGpus) AS OccD\r\nFROM vast.machines"
    }
   ]
  },
  {
   "title": "Machine revenue",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "vast",
     "rawSql": "SELECT Time as timestamp, Hostname, EarnHour FROM vast.machines"
    }
   ]
  },
  {
   "title": "Free disk space for clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "dataset": "vast",
     "rawSql": "SELECT Time as timestamp, Hostname, DiskFreeGB\r\nFROM machines"
    }
   ]
  }
 ]
}