{
 "title": "Farm overview",
 "description": "v0.1.1",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "Machine breakdown for",
    "query": "SELECT DISTINCT(MachineID) FROM vast.machines;"
   }
  ]
 },
 "panels": [
  {
   "title": "Machine revenue",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "vast",
     "rawSql": "SELECT Time as timestamp, Hostname, EarnHour FROM vast.machines"
    }
   ]
  },
  {
   "title": "Machine demand occupancy rate",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "vast",
     "rawSql": "SELECT Time as timestamp, Hostname, (NumGpusDemandOcc / NumGpus) AS OccD\r\nFROM vast.machines"
    }
   ]
  },
  {
   "title": "Machine reliability score",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT Time as timestamp, Hostname, Reliability\r\nFROM machines"
    }
   ]
  },
  {
   "title": "Machine revenue breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "vast",
     "rawSql": "SELECT \r\n  Time as timestamp, (GpuEarn + StoEarn + UploadEarn + DownloadEarn) AS Total,\r\n  GpuEarn, StoEarn, UploadEarn, DownloadEarn \r\nFROM vast.earnings\r\nWHERE MachineID = $machine;"
    }
   ]
  },
  {
   "title": "Free disk space for clients",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "dataset": "vast",
     "rawSql": "SELECT Time as timestamp, Hostname, DiskFreeGB\r\nFROM machines"
    }
   ]
  }
 ]
}